# Generated by Django 3.2.3 on 2021-05-29 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='classroom.lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='classroom.course'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.homework'),
        ),
    ]
