# Generated by Django 3.2.3 on 2021-05-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210529_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='classroom.homework'),
        ),
    ]
