# Generated by Django 3.2.3 on 2021-05-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210530_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='solution_id',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='homework_id',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='user_id',
            new_name='user',
        ),
    ]
